"""Generate a self-contained, runnable backtest script from an agent-written strategy.

The UI shows only the strategy(history) signal function in isolation; this stitches the WHOLE
pipeline together - data load -> signal -> engine -> metrics -> plot - into one standalone .py
that reproduces the result (no dependency on this app). Uses .replace() placeholders so the
template can contain real Python braces freely."""

_PERIOD_DAYS = {"6m": 126, "1y": 252, "2y": 504, "3y": 756, "5y": 1260}

_TEMPLATE = '''"""Self-contained backtest: __TICKER__, __PERIOD__ - generated by the Quant Backtester.
Reproduces the data -> signal -> P&L -> plot pipeline end to end.  Run:  python this_file.py"""
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# === 1. DATA: daily close from yfinance (download 5y, slice to the chosen period) ===
def load_prices(ticker="__TICKER__", period_days=__PERIOD_DAYS__):
    df = yf.download(ticker, period="5y", auto_adjust=True, progress=False)
    close = df["Close"]
    if isinstance(close, pd.DataFrame):          # newer yfinance returns multiindex cols
        close = close.iloc[:, 0]
    return close.dropna().tail(period_days)


# === 2. STRATEGY: the signal (history -> target position in [-1, 1]) ===
__STRATEGY_CODE__


# === 3. ENGINE: point-in-time loop + 1-bar lag (look-ahead is structurally impossible) ===
def run_backtest(prices, strategy, fee=0.0, periods_per_year=252):
    targets = pd.Series([strategy(prices.iloc[: t + 1]) for t in range(len(prices))],
                        index=prices.index, dtype=float)
    position = targets.shift(1).fillna(0.0)       # act on YESTERDAY's signal -> no same-bar fill
    asset_ret = prices.pct_change().fillna(0.0)
    turnover = position.diff().abs().fillna(position.abs())
    strat_ret = position * asset_ret - fee * turnover
    equity = (1.0 + strat_ret).cumprod()
    return equity, position


# === 4. METRICS ===
def metrics(equity, ppy=252):
    total = equity.iloc[-1] - 1.0
    cagr = (1.0 + total) ** (ppy / len(equity)) - 1.0
    ret = equity.pct_change().fillna(0.0)         # == strat_ret (equity = cumprod(1+strat_ret))
    sharpe = ret.mean() / ret.std() * np.sqrt(ppy) if ret.std() > 0 else 0.0
    max_dd = (equity / equity.cummax() - 1.0).min()
    return total, cagr, sharpe, max_dd


# === 5. RUN + PLOT: equity vs buy-and-hold + buy/sell markers + position panel ===
if __name__ == "__main__":
    prices = load_prices()
    equity, position = run_backtest(prices, strategy)
    buy_hold = prices / prices.iloc[0]
    total, cagr, sharpe, max_dd = metrics(equity)
    print(f"__TICKER__  total={total:+.1%}  CAGR={cagr:+.1%}  Sharpe={sharpe:.2f}  maxDD={max_dd:.1%}")

    entries = position[position.diff() > 0].index     # flat/short -> long  (buy)
    exits = position[position.diff() < 0].index       # long -> flat/short  (sell)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 9), sharex=True,
                                   gridspec_kw={"height_ratios": [3, 1]})
    ax1.set_title("__TICKER__  -  strategy vs buy & hold (growth of $1)")
    ax1.plot(buy_hold.index, buy_hold, color="grey", lw=0.9, label="Buy & Hold")
    ax1.plot(equity.index, equity, color="blue", lw=1.1, label="Strategy")
    ax1.plot(entries, equity.reindex(entries), "^", color="green", ms=7, label="Buy")
    ax1.plot(exits, equity.reindex(exits), "v", color="red", ms=7, label="Sell")
    ax1.legend(); ax1.grid(True, alpha=0.3)

    ax2.fill_between(position.index, position, step="pre", color="blue", alpha=0.25)
    ax2.set_ylabel("Position"); ax2.set_ylim(-1.1, 1.1); ax2.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()
'''


def full_script(strategy_code, ticker="SPY", period="2y") -> str:
    """Assemble a standalone backtest script reproducing the app's data + engine + metrics."""
    days = _PERIOD_DAYS.get(period, 504)
    return (_TEMPLATE
            .replace("__TICKER__", ticker)
            .replace("__PERIOD__", period)
            .replace("__PERIOD_DAYS__", str(days))
            .replace("__STRATEGY_CODE__", strategy_code.strip()))


_CONTRIB_TEMPLATE = '''"""Self-contained CONTRIBUTION backtest: __TICKER__ since __START__, $__AMOUNT__ per deposit.
Compares buy-the-signal vs monthly DCA in DOLLARS. Run:  python this_file.py"""
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# === 1. DATA ===
prices = yf.download("__TICKER__", start="__START__", auto_adjust=True, progress=False)["Close"]
if isinstance(prices, pd.DataFrame):
    prices = prices.iloc[:, 0]
prices = prices.dropna()


# === 2. SIGNAL: the deposit signal (history -> 1.0 = deposit on this bar) ===
__STRATEGY_CODE__


# === 3. CONTRIBUTION ENGINE: deposit $amount on each date, track units -> dollar value ===
def run_contributions(prices, deposit_dates, amount):
    deposit_set = set(pd.DatetimeIndex(deposit_dates))
    units, values, n = 0.0, [], 0
    for date, px in prices.items():
        if date in deposit_set:
            units += amount / px
            n += 1
        values.append(units * px)
    return pd.Series(values, index=prices.index), amount * n, float(values[-1])

def signal_dates(prices, strategy):
    fires = np.array([strategy(prices.iloc[: t + 1]) > 0 for t in range(len(prices))])
    return prices.index[fires]

def monthly_dates(prices):
    return prices.index[~prices.index.to_period("M").duplicated()]


# === 4. RUN + COMPARE (in dollars) ===
AMOUNT = __AMOUNT__
sig_curve, sig_inv, sig_final = run_contributions(prices, signal_dates(prices, strategy), AMOUNT)
dca_curve, dca_inv, dca_final = run_contributions(prices, monthly_dates(prices), AMOUNT)
print(f"Buy-the-signal: invested ${sig_inv:>10,.0f} -> ${sig_final:>11,.0f}  ({sig_final/sig_inv:.2f}x)")
print(f"Monthly DCA   : invested ${dca_inv:>10,.0f} -> ${dca_final:>11,.0f}  ({dca_final/dca_inv:.2f}x)")
print("Compare the MULTIPLE, not the absolute final (deposit totals differ).")

# === 5. PLOT: portfolio value over time ===
plt.figure(figsize=(14, 7))
plt.plot(sig_curve.index, sig_curve, label="Buy-the-signal")
plt.plot(dca_curve.index, dca_curve, label="Monthly DCA")
plt.title("__TICKER__  -  portfolio value, $__AMOUNT__ per deposit")
plt.ylabel("Portfolio value ($)")
plt.legend(); plt.grid(True, alpha=0.3); plt.tight_layout()
plt.show()
'''


def full_contribution_script(strategy_code, ticker="SPY", start="2021-01-01", amount=1000.0) -> str:
    """Assemble a standalone contribution backtest (signal-deposits vs monthly DCA, in dollars)."""
    return (_CONTRIB_TEMPLATE
            .replace("__TICKER__", ticker)
            .replace("__START__", str(start))
            .replace("__AMOUNT__", f"{amount:.0f}")
            .replace("__STRATEGY_CODE__", strategy_code.strip()))
